name: CI

on: [push, pull_request]

env:
  GOPATH: ${{ github.workspace }}/..

jobs:

  gotool:
    name: 'scripts/main.go'
    runs-on: 'ubuntu-latest'

    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: src/github.com/${{ github.repository }}

    - name: Build
      run: cd scripts && go build main.go

    - name: Test
      run: cd scripts && go test ./...
